tableless_model_author:
    resource: "@TablelessModelBundle/Controller/AuthorController.php"
    type:     annotation

tableless_model_post:
    resource: "@TablelessModelBundle/Controller/PostController.php"
    type:     annotation

tableless_core:
    resource: "@TablelessCoreBundle/Controller/"
    type:     annotation
    prefix:   /

